"""Read-only stdlib-only adjudication of exact adapter pending-completion captures."""
import base64,hashlib,json,pathlib,sys
PINS={'etcd':'030b4b2efd1bcc9ab043080c35f7bb68551e962b23efe62e2f2713429bd9e0f2','etcdctl':'18416269c49d0f25624938b0b45d5bd5d3eb980ab92048dc4652c66a4246141e'}
def need(v,label):
    if not v:raise ValueError(label)
def canon(v):return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False)
def enc(s):return base64.b64encode(s.encode()).decode()
def dec(s):return base64.b64decode(s,validate=True).decode()
def digest(v):return hashlib.sha256(json.dumps(v,separators=(',',':'),ensure_ascii=False).encode()).hexdigest()
def verify(root):
    root=pathlib.Path(root)
    def load(n):return json.loads((root/(n+'.json')).read_text())
    inventory={str(p.relative_to(root)):hashlib.sha256(p.read_bytes()).hexdigest() for p in root.rglob('*') if p.is_file() and p.name!='EVIDENCE_MANIFEST.json'};need(inventory==load('EVIDENCE_MANIFEST'),'INVENTORY');s=load('STATUS');need(s['status']=='OBSERVATIONS_COMPLETE_PENDING_ADJUDICATION' and s['classification']=='NONCLAIM' and s['controlling_pass']==186 and s['promotion'] is s['freeze'] is False,'STATUS');identity=load('IDENTITY');need(identity['binary_sha256']==PINS and all(inventory[n]==h for n,h in identity['sources'].items()),'IDENTITY');cfg=load('CONFIGURATION');need(cfg['members']==1 and cfg['tls'] is False and cfg['endpoints'][0].startswith('http://127.0.0.1:'),'OWNED_CLUSTER')
    def command(name,args):
        r=load(name);need(pathlib.Path(r['argv'][0]).name=='etcdctl' and r['argv'][1:]==['--endpoints='+cfg['endpoints'][0],'--command-timeout=2s','--dial-timeout=1s','--write-out=json']+args and r['returncode']==0 and r['start_monotonic_ns']<r['end_monotonic_ns'],'EXACT_COMMAND_'+name);return r
    statuses=[]
    for name in ['endpoint_before','endpoint_after']:
        r=command(name,['endpoint','status']);d=json.loads(r['stdout']);need(len(d)==1 and d[0]['Endpoint']==cfg['endpoints'][0],'ENDPOINT');statuses.append(d[0]['Status'])
    cid=statuses[0]['header']['cluster_id'];mid=statuses[0]['header']['member_id'];need(statuses[1]['header']['cluster_id']==cid and statuses[1]['header']['member_id']==mid and statuses[0]['leader']==statuses[1]['leader']==mid,'UNCHANGED_PROVIDER')
    calls=load('CALLS');exchanges=load('HTTP_EXCHANGES');expected=['late_commit:initial_activation','late_commit:before_reconcile','late_commit:after_reconcile','late_commit:final_exact_retry','retry_pending:initial_activation','retry_pending:before_reconcile','retry_pending:pending_exact_retry','retry_pending:after_reconcile','retry_pending:final_exact_retry'];need([c['label'] for c in calls]==expected,'CALLS');cursor=0
    for c in calls:need(c['exchange_start']==cursor and c['start_monotonic_ns']<c['end_monotonic_ns'],'CALL_BOUNDS');cursor=c['exchange_end'];need(cursor<=len(exchanges),'EXCHANGE_BOUNDS')
    need(cursor==len(exchanges)==17,'COMPLETE_EXCHANGES')
    def chunk(name):
        c=calls[expected.index(name)];return c,exchanges[c['exchange_start']:c['exchange_end']]
    def header(d):need(d['header']['cluster_id']==str(cid) and d['header']['member_id']==str(mid),'GATEWAY_IDENTITY')
    def normal_range(e,key):
        need(e['path']=='/v3/kv/range' and json.loads(dec(e['request_b64']))=={'key':enc(key),'serializable':False} and e['transport_error'] is None and e['response_b64'] is not None and e['authorization_present'] is False,'NORMAL_RANGE');d=json.loads(dec(e['response_b64']));header(d);return d
    def read(name,key,value=None,mod=None,create=None,version=None):
        r=command(name,['get',key,'--consistency=l']);d=json.loads(r['stdout']);need(d['header']['cluster_id']==cid and d['header']['member_id']==mid,'RAW_READ_IDENTITY')
        if value is None:need(not d.get('kvs') and d.get('count',0)==0,'ABSENT_'+name)
        else:need(d['count']==1 and len(d['kvs'])==1 and d['kvs'][0]=={'key':enc(key),'value':enc(value),'mod_revision':mod,'create_revision':create,'version':version},'FULL_KEY_RECORD_'+name)
        return r
    for case,initrev,commitrev,retry_pending in [('late_commit',2,3,False),('retry_pending',4,5,True)]:
        f=load(case+'_FIXTURE');b=f['binding'];keys=f['keys'];namespace=b['namespace'];need(b['cluster_id']==str(cid) and b['authority_config']=='C1' and b['auth_mode']=='none' and b['tls'] is False and b['adapter_version']=='pass219-etcd-nonclaim-v1' and b['endpoint'].startswith('http://127.0.0.1:') and f['retry_pending'] is retry_pending,'BINDING');need(hashlib.sha256(canon(b).encode()).hexdigest()==f['binding_digest'],'BINDING_DIGEST');rd=digest(['registry-v1','C1',[['test-domain','issuer-1','key-1','C1',f['issuer_public_key']]]]);need(rd==f['registry_digest'],'REGISTRY_DIGEST')
        eid=case+'-execution';effect=digest(['effect-v1',case,'publish',case+'-target']);need(keys=={'head':namespace+'/authority-current','receipt':namespace+'/transition/'+case,'execution':namespace+'/execution/'+eid,'outbox':namespace+'/outbox/'+effect},'EXACT_KEYS');env={'domain':'BRAINS10/EXECUTION-ENVELOPE/v1','execution_id':eid,'trust_domain':'test-domain','issuer_id':'issuer-1','key_id':'key-1','authority_config':'C1','subject_digest':'subject-1','config_digest':'config-1','input_digest':'input-1','result_digest':'result-1','runtime_id':'runtime-1'};efp=hashlib.sha256(canon(env).encode()).hexdigest();need(f['envelope']==env and f['envelope_fingerprint']==efp,'EXACT_ENVELOPE');effects=[['publish',case+'-target',case+'-payload']];fp=digest(['tx-v1','0','HEAD-A','HEAD-B',case,'C1',json.dumps(effects,separators=(',',':'))]);result={'generation':1,'head_digest':'HEAD-B','authority_config':'C1'}
        state={'generation':0,'head_digest':'HEAD-A','authority_config':'C1','lifecycle_generation':7,'registry_digest':rd,'provider_binding_digest':f['binding_digest']};next_state={**state,'generation':1,'head_digest':'HEAD-B'};vals={'head':canon(next_state),'receipt':canon({'transition_id':case,'fingerprint':fp,'execution_id':eid,'envelope_fingerprint':efp,'result':result}),'execution':canon({'execution_id':eid,'envelope_fingerprint':efp,'transition_id':case}),'outbox':canon({'effect_id':effect,'transition_id':case,'kind':'publish','target':case+'-target','payload':case+'-payload','generation':1,'authority_config':'C1'})}
        init=command(case+'_initialize',['txn']);j=json.dumps;need(init['stdin']==f'version({j(keys["head"])}) = "0"\n\nput {j(keys["head"])} {j(canon(state))}\n\nget {j(keys["head"])}\n\n' and json.loads(init['stdout'])['succeeded'] is True,'INITIALIZE')
        compares=[{'key':enc(keys['head']),'target':'MOD','result':'EQUAL','modRevision':str(initrev)},{'key':enc(keys['head']),'target':'VALUE','result':'EQUAL','value':enc(canon(state))}]+[{'key':enc(keys[n]),'target':'VERSION','result':'EQUAL','version':'0'} for n in ['receipt','execution','outbox']];txn={'compare':compares,'success':[{'requestPut':{'key':enc(keys[n]),'value':enc(vals[n])}} for n in ['head','receipt','execution','outbox']],'failure':[]};body=canon(txn)
        c,es=chunk(case+':initial_activation');need(c['outcome']=='UNKNOWN_COMMIT' and c['result']=={'transition_id':case,'fingerprint':fp} and len(es)==3,'PENDING_UNKNOWN');d=normal_range(es[0],keys['head']);need(dec(d['kvs'][0]['value'])==canon(state) and int(d['kvs'][0]['mod_revision'])==initrev,'EXACT_PARENT');need(not normal_range(es[1],keys['receipt']).get('kvs'),'NO_PRIOR_RECEIPT');original=es[2];need(original['path']=='/v3/kv/txn' and dec(original['request_b64'])==body and original['transport_error']=='TimeoutError' and original['response_b64'] is None,'ACTUAL_TIMEOUT')
        transport=load(case+'_TRANSPORT_CONFIG');need(transport['endpoint']==b['endpoint'] and transport['upstream']==cfg['endpoints'][0] and transport['namespace_prefix']==namespace+'/' and transport['witness_used_for_reconciliation'] is False,'FIXED_TRANSPORT');events=load(case+'_TRANSPORT_EVENTS');accepted=[e for e in events if e['event']=='accepted'];need(len(accepted)<=32 and len({e['request_index'] for e in accepted})==len(accepted),'REQUEST_CAP');held=[e for e in accepted if e['held']];need(len(held)==1 and held[0]['body']==body and held[0]['path']=='/v3/kv/txn','HELD_EXACT_REQUEST');held=held[0];idx=held['request_index'];release=[e for e in events if e['event']=='release'];forwards=[e for e in events if e['event']=='forward' and e['request_index']==idx];witnesses=[e for e in events if e['event']=='upstream_complete' and e['request_index']==idx];need(len(release)==len(forwards)==len(witnesses)==1,'HELD_LIFECYCLE');release=release[0];forward=forwards[0];witness=witnesses[0];need(c['start_monotonic_ns']<held['monotonic_ns']<c['end_monotonic_ns']<release['monotonic_ns']<forward['monotonic_ns']<witness['monotonic_ns'],'TIMEOUT_FORWARD_ORDER')
        before,es=chunk(case+':before_reconcile');need(before['outcome']=='UNKNOWN_COMMIT' and before['result'] is None and len(es)==1 and not normal_range(es[0],keys['receipt']).get('kvs'),'ABSENCE_UNKNOWN');need(c['end_monotonic_ns']<before['start_monotonic_ns']<before['end_monotonic_ns']<release['monotonic_ns'],'ABSENCE_ORDER')
        for n,key in keys.items():
            rr=read(case+'_before_'+n,key,canon(state) if n=='head' else None,initrev,initrev,1);need(before['end_monotonic_ns']<rr['start_monotonic_ns']<rr['end_monotonic_ns']<release['monotonic_ns'],'PENDING_STATE_ORDER')
        wd=json.loads(witness['response']);header(wd);need(wd.get('succeeded',False) is (not retry_pending) and int(wd['header']['revision'])==commitrev,'LATE_TXN_OUTCOME')
        if retry_pending:
            retry,es=chunk(case+':pending_exact_retry');need(retry['outcome']=='OK' and retry['result']==result and len(es)==3 and before['end_monotonic_ns']<retry['start_monotonic_ns']<retry['end_monotonic_ns']<release['monotonic_ns'],'PENDING_RETRY');normal_range(es[0],keys['head']);need(not normal_range(es[1],keys['receipt']).get('kvs'),'RETRY_ABSENCE');tx=es[2];need(tx['path']=='/v3/kv/txn' and tx['request_b64']==original['request_b64'] and tx['transport_error'] is None,'BYTE_IDENTICAL_RETRY');td=json.loads(dec(tx['response_b64']));header(td);need(td['succeeded'] is True and int(td['header']['revision'])==commitrev,'RETRY_COMMIT');commit=td
            for n in vals:read(case+'_pending_retry_'+n,keys[n],vals[n],commitrev,initrev if n=='head' else commitrev,2 if n=='head' else 1)
        else:commit=wd
        need(len(commit['responses'])==4 and all(int(r['response_put']['header']['revision'])==commitrev for r in commit['responses']),'ATOMIC_FOUR_WRITES')
        after,es=chunk(case+':after_reconcile');need(after['outcome']=='OK' and after['result']==result and len(es)==1 and after['start_monotonic_ns']>witness['monotonic_ns'],'AFTER_RECONCILIATION');d=normal_range(es[0],keys['receipt']);need(dec(d['kvs'][0]['value'])==vals['receipt'],'FULL_RECONCILIATION_RECEIPT')
        for n in vals:read(case+'_after_'+n,keys[n],vals[n],commitrev,initrev if n=='head' else commitrev,2 if n=='head' else 1)
        final,es=chunk(case+':final_exact_retry');need(final['outcome']=='OK' and final['result']==result and len(es)==2,'REPLAY_NO_TXN');need(dec(normal_range(es[0],keys['head'])['kvs'][0]['value'])==vals['head'] and dec(normal_range(es[1],keys['receipt'])['kvs'][0]['value'])==vals['receipt'],'REPLAY_RECORDS')
        for n in vals:
            rr=read(case+'_final_'+n,keys[n],vals[n],commitrev,initrev if n=='head' else commitrev,2 if n=='head' else 1);need(rr['start_monotonic_ns']>final['end_monotonic_ns'],'FINAL_ORDER')
        cleanup=[e for e in events if e['event']=='cleanup'];need(len(cleanup)==1 and cleanup[0]['active_workers']==0 and cleanup[0]['server_thread_alive'] is False and cleanup[0]['errors']==[] and not any(e['event']=='handler_error' for e in events),'TRANSPORT_CLEANUP')
        need(any(e['event']=='late_response_not_delivered' and e['request_index']==idx for e in events),'WITNESS_ONLY')
    events=load('PROCESS_EVENTS');starts=[e for e in events if e['action']=='start'];exits=[e for e in events if e['action']=='exit'];need(len(starts)==len(exits)==1 and starts[0]['pid']==exits[0]['pid'] and starts[0]['start_number']==0 and exits[0]['monotonic_ns']>calls[-1]['end_monotonic_ns'],'OWNED_PROCESS_CLEANUP')
    return {'verification':'PASS','classification':'NONCLAIM','controlling_pass':186,'promotion':False,'freeze':False,'scope':'unchanged adapter pending late commit and identical retry; four atomic state/consequence keys','evidence_files':len(inventory),'adapter_calls':len(calls),'http_exchanges':len(exchanges)}
if __name__=='__main__':
    try:print(json.dumps(verify(sys.argv[1]),sort_keys=True))
    except Exception as e:print(json.dumps({'verification':'REJECTED','error':type(e).__name__+': '+str(e)}));raise SystemExit(2)
